<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0-windows</TargetFramework>
    <RootNamespace>VCS_DOCs.Notifications</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClamAV.Net" Version="0.1.166" />
  </ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\\VCS-DOCs.Models\\VCS-DOCs.Models.csproj" />
		<ProjectReference Include="..\\VCS-DOCs.Core\\VCS-DOCs.Core.csproj" />
	</ItemGroup>
</Project>
