<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>VCS_DOCs.WebCAD</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClamAV.Net" Version="0.1.166" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="9.0.9" />
  </ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\\VCS-DOCs.Models\\VCS-DOCs.Models.csproj" />
		<ProjectReference Include="..\\VCS-DOCs.Configuration\\VCS-DOCs.Configuration.csproj" />
	</ItemGroup>
</Project>
